# spring.application.name=ecommerce

#---Ruta de donde estará la base de datos
spring.datasource.url=${DB_URL}

#---Credenciales de mysql para que haga la conexión correcta
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#---Indicarle que usaremos el driver JDBC para que se conecte con la base de datos
spring.datasource.drive-class-name=com.mysql.cj.jdbc.Driver

#---SPRING CONFIG
#---Vamos a decir que va a pasar cuando iniciemos spring
spring.jpa.hibernate.ddl-auto=create-drop

#---visualizar consultas sql
spring.jpa.show-sql=true
spring.jpa.hibernate.format-sql=true
server.port=8080
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#-----------------------AQUI INICIA LA CONFIGURACIÓN PARA PRODUCCIÓN -------------------------

#------SPRING JPA LOGGIN
#spring.jpa.properties.hibernate.format_sql=true
#------HIBERNATE LOGIN
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=trace
